spring:
  application:
    name: "user-service"
  data:
    mongodb:
      uri: "${MONGODB_URI}/db"

springdoc:
  swagger-ui:
    path: /api/user/swagger/ui
  api-docs:
    path: /api/user/swagger/docs

server:
  port: 8082

management:
  otlp:
    tracing:
      endpoint: "${GRAFANA_OTLP_ENDPOINT}/v1/traces"
      headers:
        Authorization: "Basic ${GRAFANA_TEMPO_USER_PASS_BASE64_ENCODED}"
  zipkin:
    tracing:
      endpoint: "http://${ZIPKIN_HOST}/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO

security:
  config:
    excludedUrls: >
      /api/user/swagger/**,
      /api/user/signup