spring:
  application:
    name: "product-service"
  data:
    mongodb:
      uri: "${MONGODB_URI}/db"
  kafka:
    bootstrap-server: localhost:9092
    properties:
      #Server host name verification is disabled by setting ssl.endpoint.identification.algorithm to an empty string
      ssl.endpoint.identification.algorithm:

  #APP SPECIFIC CUSTOM PROPERTIES
  app:
    kafka:
      producer:
        topic: <>
      consumer:
        topic: <order_revert_inventory>

springdoc:
  swagger-ui:
    path: /api/product/swagger/ui
  api-docs:
    path: /api/product/swagger/docs

server:
  error:
    whitelabel:
      enabled: false
  port: 8083

management:
  otlp:
    tracing:
      endpoint: "${GRAFANA_OTLP_ENDPOINT}/v1/traces"
      headers:
        Authorization: "Basic ${GRAFANA_TEMPO_USER_PASS_BASE64_ENCODED}"
  zipkin:
    tracing:
      endpoint: "${ZIPKIN_URI}/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO

security:
  config:
    excludedUrls: >
      /api/product/swagger/**,
      /api/product/get/**