spring:
  application:
    name: "order-service"
  data:
    mongodb:
      uri: "${MONGODB_URI}/db"
  kafka:
    bootstrap-server: localhost:9092
    service:
      name: "order-service"
    properties:
      #Server host name verification is disabled by setting ssl.endpoint.identification.algorithm to an empty string
      ssl.endpoint.identification.algorithm:

#APP SPECIFIC CUSTOM PROPERTIES
app:
  kafka:
    producer:
      topic: <order_revert_inventory>
    consumer:
      topic: <order_payment_failed, order_payment_success>

springdoc:
  swagger-ui:
    path: /api/order/swagger/ui
  api-docs:
    path: /api/order/swagger/docs

server:
  error:
    whitelabel:
      enabled: false
  port: 8084

management:
  otlp:
    tracing:
      endpoint: "${GRAFANA_OTLP_ENDPOINT}/v1/traces"
      headers:
        Authorization: "Basic ${GRAFANA_TEMPO_USER_PASS_BASE64_ENCODED}"
  zipkin:
    tracing:
      endpoint: "${ZIPKIN_URI}/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO

security:
  config:
    excludedUrls: >
      /api/order/swagger/**,
      /api/order/get/**