spring:
  application:
    name: "gateway-service"
  main:
    web-application-type: reactive

server:
  error:
    whitelabel:
      enabled: false
  port: 8080

management:
  otlp:
    tracing:
      endpoint: "${GRAFANA_OTLP_ENDPOINT}/v1/traces"
      headers:
        Authorization: "Basic ${GRAFANA_TEMPO_USER_PASS_BASE64_ENCODED}"
  zipkin:
    tracing:
      endpoint: "http://${ZIPKIN_HOST}/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO