spring:
  application:
    name: "auth-service"
  data:
    mongodb:
      uri: "${MONGODB_URI}/db"

springdoc:
  swagger-ui:
    path: /api/auth/swagger/ui
  api-docs:
    path: /api/auth/swagger/docs

server:
  port: 8081

management:
  otlp:
    tracing:
      endpoint: "${GRAFANA_OTLP_ENDPOINT}/v1/traces"
      headers:
        Authorization: "Basic ${GRAFANA_TEMPO_USER_PASS_BASE64_ENCODED}"
  zipkin:
    tracing:
      endpoint: "${ZIPKIN_URI}/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
  path: "C:\\Users\\abhis_ldm1adl\\Documents\\development\\e-commerce-backend\\logfile.txt"

jwt:
  secret: "${SECRET_KEY}"
