spring:
  application:
    name: "payment-service"
  data:
    mongodb:
      uri: "${MONGODB_URI}/db"
  kafka:
    bootstrap-server: "localhost:9092"

springdoc:
  swagger-ui:
    path: /api/payment/swagger/ui
  api-docs:
    path: /api/payment/swagger/docs

server:
  error:
    whitelabel:
      enabled: false
  port: 8085

management:
  zipkin:
    tracing:
      endpoint: "${ZIPKIN_URI}/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO